name: cafe_mostbyte
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_styled_toast: ^2.0.0
  flutter_svg: ^0.22.0
  shared_preferences: ^2.0.8
  fluttertoast: ^8.0.8
  cached_network_image: ^3.1.0
  skeleton_text: ^3.0.0
  flutter_form_builder: ^6.0.1
  device_info: ^2.0.2
  auto_size_text: ^3.0.0
  confirm_dialog: ^1.0.0
  path_provider: ^2.0.8
  
  connectivity: ^3.0.6
  http: ^0.13.3
  flutter_bloc: ^7.1.0
  rxdart: ^0.27.2
  equatable: ^2.0.3
  html: ^0.15.0
  url_launcher: ^6.0.10
  image: ^3.0.8

  window_manager: ^0.1.1

  # system_theme: ^1.0.1
  flutter_typeahead: ^3.2.1
  flutter_login: ^3.0.0
  webcontent_converter: ^0.0.7
  pos_printer_manager: ^0.0.5
  extended_masked_text: ^2.2.1
  platform: ^3.1.0
  flutter_vector_icons: ^1.0.0
  flutter_phoenix: ^1.0.0
  barcode: ^2.2.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  # flutter_launcher_icons: ^0.7.0
flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/launcher/launch_icon.png"
  image_path_android: "assets/launcher/launch_icon.png"
  image_path: "assets/launcher/launch_icon.png"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    #localozation files
    - locales/EN_US.json
    - locales/UZ_UZ.json
    - locales/OZ_OZ.json
    - locales/RU_RU.json
    # image in app
    - assets/img/shopping_cart.svg
    - assets/img/home_icon.svg
    - assets/img/home_selected.svg
    - assets/img/fire_icon.svg
    - assets/img/fire_selected.svg
    - assets/img/bin.svg
    - assets/img/logo.png
    - assets/img/clear.svg
    - assets/img/down-arrow.svg
    - assets/img/up-arrow.svg
    - assets/img/minus.svg
    - assets/img/plus.svg
    - assets/img/eye.svg
    - assets/img/visibility.svg
    - assets/img/no-photo.svg
    - assets/img/logo-cafe.svg
    - assets/img/logo.jpg
    - assets/img/logo-transparent.png
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
        - asset: assets/fonts/Raleway-Medium.ttf
          weight: 500
        - asset: assets/fonts/Raleway-Medium.ttf
          weight: 500
        - asset: assets/fonts/Raleway-Semibold.ttf
          weight: 600
        - asset: assets/fonts/Raleway-Bold.ttf
          weight: 900
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
